### ISSUE TITLE
Puppet 4 support

### ISSUE THREAD

**Issue by sknolin** [hercules-team/augeasproviders_pam#15]
Are there plans to make this compatible with Puppet 4.x?

**Comment by raphink** [comment]
@sknolin how is it not compatible with Puppet 4?

**Comment by sknolin** [comment]
I just read this - https://forge.puppet.com/herculesteam/augeasproviders_pam/compatibility

> Version 2.1.0 is compatible with:
> 
> Puppet Enterprise 3.8.x, 3.7.x, 3.3.x, 3.2.x, 3.1.x
> Puppet >= 2.7.0 < 4.0.0

Maybe this issue should just be 'update forge compatibility page' is all then? :)

**Comment by raphink** [comment]
Ah well, I think we haven't updated it since Puppet 4 came out.

**Comment by raphink** [comment]
Actually, `puppet_version` is deprecated in `metadata.json` according to docs. @domcleal would you like to remove that info altogether?

**Comment by domcleal** [comment]
Only "puppet_version" was deprecated, the "requirements" key (containing another list of Puppet versions) is still expected and should include 4.x if the module's indeed tested and works with it.

**Comment by raphink** [comment]
Ah, right. So I'll remove the `puppet_version` sections and update the `requirements` to go up to `4.5`. Good for you?

**Comment by raphink** [comment]
Or maybe `< 5.0.0`

**Comment by raphink** [comment]
I might as well update Ubuntu supported versions, too. It changes every 6 months, to ;-)

**Comment by sknolin** [comment]
Is the forge not linked to metadata.json in the source? Or does it just show up whenever you push a new version out? I tend to just look at that anyhow, but gets confusing.

**Comment by raphink** [comment]
The forge info is only updated when a new release is pushed.
