### ISSUE TITLE
Cannot insert a line both before and after

### ISSUE THREAD

**Issue by linuxdan** [hercules-team/augeasproviders_pam#19]
Starting with default RHEL 7 /etc/pam.d/system-auth :
[system-auth.txt](https://github.com/hercules-team/augeasproviders_pam/files/1363322/system-auth.txt)
And trying to apply DISA STIG modifications:
 To configure the system to lock out accounts after a number of incorrect login attempts using pam_faillock.so, modify the content of both /etc/pam.d/system-auth and /etc/pam.d/password-auth as follows:
    add the following line immediately before the pam_unix.so statement in the AUTH section:
`    auth required pam_faillock.so preauth silent deny=3 unlock_time=never fail_interval=900`
    add the following line immediately after the pam_unix.so statement in the AUTH section:
`    auth [default=die] pam_faillock.so authfail deny=3 unlock_time=never fail_interval=900`

with this bit of puppet code:
[snippet.pp.txt](https://github.com/hercules-team/augeasproviders_pam/files/1363333/snippet.pp.txt)
and what I get is ...
[log.txt](https://github.com/hercules-team/augeasproviders_pam/files/1363348/log.txt)
resulting in 
[system-auth-after.txt](https://github.com/hercules-team/augeasproviders_pam/files/1363349/system-auth-after.txt)

Now is this a bug or did I mess up ?

**Comment by eric4tech** [comment]
I know this is a bit old, but I may be running into something similar. Though it's possible adding control_is_param will help you. It did not help me. 

In your pam resource declaration, just add control_is_param => true, and see if that works. If you don't have it working already.

**Comment by linuxdan** [comment]
That makes the difference
