### ISSUE TITLE
Question: Can any file name in /etc/pam.d be used as the "service" parameter ?

### ISSUE THREAD

**Issue by linuxdan** [hercules-team/augeasproviders_pam#22]
The only "services" referenced in code or docs are service-auth and password-auth

**Comment by raphink** [comment]
The `service` attribute is used to refer to the file in `/etc/pam.d`, so I can't think of a restriction.

**Comment by linuxdan** [comment]
Thanks for the encouraging response.
I will tinker a bit and let you know my results.

**Comment by linuxdan** [comment]
@raphink 
`puppet resource pam`   says `Error: could not run: No resource and no name in property hash in augeas instance`
I am looking for a way to see how existing files are perceived by this module - so I can create them from scratch

**Comment by linuxdan** [comment]
FYI: It works - a file is created in /etc/pam.d with the name {service}
