### ISSUE TITLE
Ability to delete more specific items

### ISSUE THREAD

**Issue by fgimian** [hercules-team/augeasproviders_pam#7]
Hey there, still loving this library (it's a lifesaver) :smile: 

Perhaps I'm missing something, but it seems that the `absent` keyword doesn't look at the `control` passed in:

e.g.

```puppet
  pam { 'remove sufficient unix auth instance from system-auth':
    ensure  => absent,
    service => 'system-auth',
    type    => 'auth',
    control => 'sufficient',
    module  => 'pam_unix.so',
  }
```

This seems to remove `pam_unix.so` regardless of the control.

Is it possible to be more specific when removing entries like this?

Thanks
Fotis

**Comment by raphink** [comment]
There is a `control_is_param` parameter which lets you decide if `control` should be treated as a parameter or a property. Set it to `false` and it should do what you want.

**Comment by fgimian** [comment]
@raphink that did the trick, thanks a million for replying so fast!! :smile:
