### ISSUE TITLE
Module doesn't allow more than one line with same module

### ISSUE THREAD

**Issue by markasammut** [hercules-team/augeasproviders_pam#9]
The below for example cannot be implemented:

auth        required      pam_env.so
auth        required      pam_faillock.so preauth audit silent deny=6 unlock_time=1800
auth        sufficient    pam_fprintd.so
auth        sufficient    pam_unix.so nullok try_first_pass
auth        [default=die] pam_faillock.so authfail deny=6 unlock_time=1800
auth        sufficient    pam_faillock.so authsucc deny=6 unlock_time=1800
auth        requisite     pam_succeed_if.so uid >= 500 quiet
auth        required      pam_deny.so

as pam_faillock.so appears in more than one line.

**Comment by raphink** [comment]
This is possible by setting different parameters, and making sure titles are unique. Also, you can even have the same control field by using `control_is_param => true`.

**Comment by markasammut** [comment]
Yes, I required the control_is_param to be set to have it work.

Thanks!
